<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useLocaleStore} from '@/stores/locale'
import {requestJson,CustomerSessionApiError} from '@/features/auth/services/customerSessionApi'
import type {TrackedOrder} from '../services/trackingApi'
const props=defineProps<{order:TrackedOrder;admin?:boolean}>(),emit=defineEmits<{updated:[TrackedOrder]}>(),locale=useLocaleStore()
const texts={fa:['اقلام و مبلغ سفارش','واحد پول','شرح کالا','کد محصول (اختیاری)','تعداد','قیمت واحد','افزودن ردیف','حذف ردیف','هزینه ارسال','تخفیف','مالیات','جمع کل','دلیل ثبت / اصلاح','ذخیره مبلغ و اقلام','فایل‌های سفارش','فاکتور','رسید پیش‌پرداخت','نمایش فایل به مشتری','بارگذاری فایل','دریافت فایل','پس از تأیید فاکتور، اقلام و مبلغ قفل می‌شوند.','هنوز مبلغی ثبت نشده است.'],en:['Order items & amount','Currency','Item description','Product code (optional)','Quantity','Unit price','Add row','Remove row','Shipping','Discount','Tax','Total','Reason for change','Save quote','Order files','Invoice','Deposit receipt','Show file to customer','Upload file','Download','Confirmed invoices lock quote details.','No quote yet.'],ar:['أصناف الطلب والمبلغ','العملة','وصف الصنف','رمز المنتج (اختياري)','الكمية','سعر الوحدة','إضافة صف','حذف الصف','الشحن','الخصم','الضريبة','الإجمالي','سبب التعديل','حفظ المبلغ','ملفات الطلب','الفاتورة','إيصال الدفعة','إظهار الملف للعميل','رفع الملف','تنزيل','تفاصيل الفاتورة المؤكدة مقفلة.','لا يوجد مبلغ مسجل.'],ku:['کاڵاکان و بڕ','دراو','وەسفی کاڵا','کۆدی کاڵا','ژمارە','نرخی تاک','زیادکردنی ڕیز','سڕینەوەی ڕیز','ناردن','داشکاندن','باج','کۆی گشتی','هۆکاری گۆڕان','پاشەکەوتکردن','فایلەکان','فاکتۆر','پسولەی پێشەکی','پیشاندانی فایل بۆ کڕیار','بارکردنی فایل','داگرتن','فاکتۆری پشتڕاستکراو داخراوە.','بڕ تۆمار نەکراوە.']}
const w=(i:number)=>texts[locale.locale][i]??''
const currency=ref('IRT'),lines=ref<{description:string;product_code:string;quantity:number;price:string}[]>([]),shipping=ref('0'),discount=ref('0'),tax=ref('0'),reason=ref(''),kind=ref('invoice'),visible=ref(false),busy=ref(false),error=ref('')
const scale=computed(()=>['USD','EUR','AED'].includes(currency.value)?100:1)
const mutable=computed(()=>props.admin&&!props.order.invoice_confirmed_at&&!['cancelled','delivered'].includes(props.order.stage))
const labels={IRR:'ریال',IRT:'تومان',USD:'USD',EUR:'EUR',IQD:'IQD',AED:'AED'}
function minor(value:string){const parts=/^(\d{1,12})(?:\.(\d{1,2}))?$/.exec(value.trim());if(!parts||scale.value===1&&parts[2])throw Error('amount');return Number(parts[1])*scale.value+(scale.value===100?Number((parts[2]??'').padEnd(2,'0')):0)}
function price(value:number){return String(value/scale.value)}
function formatted(value:number,code:string){return new Intl.NumberFormat(locale.locale==='ku'?'ar':locale.locale,{maximumFractionDigits:2}).format(value/(['USD','EUR','AED'].includes(code)?100:1))+' '+(labels[code as keyof typeof labels]??code)}
watch(()=>props.order,order=>{currency.value=order.quote?.currency??'IRT';lines.value=order.quote?.items.map(i=>({description:i.description,product_code:i.product_code??'',quantity:i.quantity,price:price(i.unit_price_minor)}))??[{description:'',product_code:'',quantity:1,price:'0'}];shipping.value=price(order.quote?.shipping_minor??0);discount.value=price(order.quote?.discount_minor??0);tax.value=price(order.quote?.tax_minor??0);reason.value=''},{immediate:true})
function fail(e:unknown){error.value=locale.t(e instanceof CustomerSessionApiError&&e.status===409?'adminConflict':'adminRequestFailed')}
async function save(){if(busy.value||!mutable.value)return;busy.value=true;error.value='';try{const response=await requestJson<{order:TrackedOrder}>('/api/admin/orders/'+props.order.id+'/quote',{method:'PUT',body:JSON.stringify({revision:props.order.revision,currency:currency.value,items:lines.value.map(i=>({description:i.description,product_code:i.product_code||null,quantity:i.quantity,unit_price_minor:minor(i.price)})),shipping_minor:minor(shipping.value),discount_minor:minor(discount.value),tax_minor:minor(tax.value),note:reason.value})});emit('updated',response.order)}catch(e){fail(e)}finally{busy.value=false}}
async function upload(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file||busy.value)return;busy.value=true;error.value='';try{const body=new FormData();body.set('revision',props.order.revision??'');body.set('kind',kind.value);body.set('visible_to_customer',visible.value?'1':'0');body.set('note',reason.value);body.set('document',file);emit('updated',(await requestJson<{order:TrackedOrder}>('/api/admin/orders/'+props.order.id+'/documents',{method:'POST',body})).order)}catch(e){fail(e)}finally{busy.value=false;input.value=''}}
</script>
<template>
 <section class="space-y-3 border-t border-[var(--c-border)] pt-3">
  <h3 class="font-bold text-sm">{{w(0)}}</h3>
  <template v-if="order.quote"><ul class="space-y-1 text-sm"><li v-for="(item,index) in order.quote.items" :key="index">{{item.description}} <span v-if="item.product_code" dir="ltr">({{item.product_code}})</span> · {{item.quantity}} × {{formatted(item.unit_price_minor,order.quote.currency)}}</li></ul><p class="text-sm">{{w(8)}}: {{formatted(order.quote.shipping_minor,order.quote.currency)}} · {{w(9)}}: {{formatted(order.quote.discount_minor,order.quote.currency)}} · {{w(10)}}: {{formatted(order.quote.tax_minor,order.quote.currency)}}</p><b>{{w(11)}}: {{formatted(order.quote.total_minor,order.quote.currency)}}</b></template><p v-else class="text-sm">{{w(21)}}</p>
  <p v-if="admin&&order.invoice_confirmed_at" class="text-xs">{{w(20)}}</p>
  <form v-if="mutable" class="space-y-2" @submit.prevent="save"><fieldset class="space-y-2" :disabled="busy">
   <label class="form-field">{{w(1)}}<select v-model="currency"><option v-for="(label,code) in labels" :key="code" :value="code">{{label}}</option></select></label>
   <div v-for="(line,index) in lines" :key="index" class="grid gap-2 rounded-lg border border-[var(--c-border)] p-2 sm:grid-cols-2">
    <label class="form-field">{{w(2)}}<input v-model="line.description" required maxlength="300"></label><label class="form-field">{{w(3)}}<input v-model="line.product_code" maxlength="64"></label><label class="form-field">{{w(4)}}<input v-model.number="line.quantity" required type="number" min="1" max="100000" step="1"></label><label class="form-field">{{w(5)}}<input v-model="line.price" required type="number" min="0" :step="scale===100?'.01':'1'"></label><button v-if="lines.length>1" type="button" class="mini-action" @click="lines.splice(index,1)">{{w(7)}}</button>
   </div><button type="button" class="mini-action" :disabled="lines.length>=50" @click="lines.push({description:'',product_code:'',quantity:1,price:'0'})">{{w(6)}}</button>
   <div class="grid gap-2 sm:grid-cols-3"><label class="form-field">{{w(8)}}<input v-model="shipping" type="number" min="0" :step="scale===100?'.01':'1'" required></label><label class="form-field">{{w(9)}}<input v-model="discount" type="number" min="0" :step="scale===100?'.01':'1'" required></label><label class="form-field">{{w(10)}}<input v-model="tax" type="number" min="0" :step="scale===100?'.01':'1'" required></label></div>
   <label class="form-field">{{w(12)}}<textarea v-model="reason" required minlength="3" maxlength="4000" rows="2"/></label><button class="mini-action">{{w(13)}}</button>
  </fieldset></form>
  <h3 class="font-bold text-sm">{{w(14)}}</h3><div v-for="document in order.documents??[]" :key="document.id" class="text-sm"><span>{{document.kind==='invoice'?w(15):w(16)}} · #{{document.id}}</span> <a :href="document.download_url" class="mini-action" target="_blank" rel="noopener">{{w(19)}}</a></div>
  <fieldset v-if="admin" :disabled="busy" class="space-y-2"><select v-model="kind" class="field-input" :aria-label="w(14)"><option value="invoice">{{w(15)}}</option><option value="deposit_receipt">{{w(16)}}</option></select><label class="form-field">{{w(12)}}<textarea v-model="reason" minlength="3" maxlength="4000" rows="2"/></label><label class="flex gap-2 text-sm"><input v-model="visible" type="checkbox">{{w(17)}}</label><label class="block text-xs">{{w(18)}} · PDF / JPG / PNG / WebP · 8 MB<input type="file" class="block max-w-full mt-2" accept="application/pdf,image/jpeg,image/png,image/webp" :disabled="reason.trim().length<3" @change="upload"></label></fieldset>
  <p v-if="error" class="auth-error" role="alert">{{error}}</p>
 </section>
</template>
