import { requestJson } from '@/features/auth/services/customerSessionApi'
export const orderStages=['inquiry','review','invoice','awaiting_deposit','production','quality','ready','shipped','delivered','cancelled'] as const
export type OrderStage=typeof orderStages[number]
export interface TrackedOrder {id:number;reference:string;customer_id?:number;request_path:string;description:string;stage:OrderStage;invoice_confirmed_at:string|null;deposit_confirmed_at:string|null;revision?:string;events:{id:number;action:string;stage:OrderStage;note:string;visible_to_customer:boolean;created_at:string}[]}
export interface OrderPage {orders:TrackedOrder[];page:number;last_page:number}
export const fetchOrders=(admin=false,page=1)=>requestJson<OrderPage>((admin?'/api/admin/orders':'/api/customer/orders')+'?page='+page)
export const createTrackedOrder=(fields:{customer_id?:number;request_path:string;description:string},admin=false)=>requestJson<{order:TrackedOrder}>(admin?'/api/admin/orders':'/api/customer/orders',{method:'POST',body:JSON.stringify(fields)})
export const updateTrackedOrder=(order:TrackedOrder,fields:{action:string;stage?:string;note:string;visible_to_customer:boolean})=>requestJson<{order:TrackedOrder}>('/api/admin/orders/'+order.id,{method:'PATCH',body:JSON.stringify({...fields,revision:order.revision})})
export const stageLabels={fa:['درخواست اولیه','بررسی مشخصات','فاکتور','انتظار پیش‌پرداخت','تولید / آماده‌سازی','کنترل کیفیت','آماده ارسال','ارسال‌شده','تحویل‌شده','لغوشده'],en:['Inquiry','Specification review','Invoice','Awaiting deposit','Production / preparation','Quality control','Ready to ship','Shipped','Delivered','Cancelled'],ar:['طلب أولي','مراجعة المواصفات','الفاتورة','انتظار الدفعة المقدمة','الإنتاج / التجهيز','مراقبة الجودة','جاهز للشحن','تم الشحن','تم التسليم','ملغي'],ku:['داواکاری سەرەتایی','پشکنینی تایبەتمەندی','فاکتۆر','چاوەڕوانی پێشەکی','بەرهەمهێنان / ئامادەکردن','پشکنینی کوالێتی','ئامادەی ناردن','نێردراو','گەیەندراو','هەڵوەشاوە']}
