function layout(){document.documentElement.lang=lang;document.documentElement.dir=tx[lang].dir;const root=$('#app');root.innerHTML=`
<header class="topbar"><div class="topbar-in"><a class="brand-mini" href="../index.htm"><img src="../../logo.png" alt="${t('brand')}"><span><b>${t('brand')}</b><small>${t('tagline')}</small></span></a><div class="top-actions"><select id="lang" class="lang-select" aria-label="Language"><option value="fa">فارسی</option><option value="ar">العربية</option><option value="en">English</option><option value="ku">کوردی</option></select></div></div></header>
<main class="main"><section id="v-home" class="view active"></section><section id="v-products" class="view"></section><section id="v-production" class="view"></section><section id="v-favorites" class="view"></section><section id="v-tracking" class="view"></section></main>
<nav class="bottom-nav" aria-label="main"><div class="bottom-nav-in">
<button class="nav-btn on" data-view="home">${I.home}<span>${t('home')}</span></button><button class="nav-btn" data-view="products">${I.grid}<span>${t('products')}</span></button><button class="nav-btn fab-order" data-view="production">${I.wand}<span>${t('production')}</span></button><button class="nav-btn" data-view="favorites">${I.heart}<span>${t('favorites')}</span></button><button class="nav-btn" data-view="tracking">${I.track}<span>${t('tracking')}</span></button>
</div></nav><div id="detailOverlay" class="overlay ${mode==='modal'?'mode-modal':'mode-sheet'}"></div><div id="actionOverlay" class="overlay mode-sheet"></div><div id="toast" class="toast"></div>`;
$('#lang').value=lang;$('#lang').onchange=e=>setLang(e.target.value);$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
renderHome();renderProducts();renderProduction();renderFavorites();renderTracking();
}
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`v-${v}`));$$('.nav-btn').forEach(x=>x.classList.toggle('on',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});if(v==='favorites')renderFavorites();if(v==='production')renderProduction();}
function renderHome(){const el=$('#v-home');el.innerHTML=`<section class="hero"><div class="eyebrow">TEST ${testNo} · ${mode==='sheet'?'ADAPTIVE SHEET':mode==='inline'?'INLINE EXPAND':'FOCUSED MODAL'}</div><h1>${t('heroTitle')}</h1><p>${t('heroText')}</p><div class="hero-actions"><button class="btn primary" data-go="products">${t('browse')}</button><button class="btn secondary" data-go="production">${t('startOrder')}</button></div></section>
<div class="demo-note">${t('demo')}</div><section class="section"><div class="section-head"><div><h2>${t('chooseCategory')}</h2><p>${t('chooseSub')}</p></div></div><div class="category-grid">${Object.keys(cats).map(id=>catCard(id)).join('')}</div></section>
<section class="section"><div class="section-head"><div><h2>${t('products')}</h2><p>${t('chooseSub')}</p></div><button class="btn ghost spacer" data-go="products">${t('browse')}</button></div><div class="product-grid">${products.filter(p=>p.variant===1).map(productCard).join('')}</div></section>
<section class="section"><div class="section-head"><div><h2>${t('brandIntro')}</h2><p>${t('placeholder')}</p></div></div><div class="trust-grid">${trustCard('capabilities',I.wand)}${trustCard('docs',I.check)}${trustCard('sales',I.phone)}</div></section>`;
$$('[data-go]',el).forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('.category-card',el).forEach(b=>b.onclick=()=>{category=b.dataset.cat;sub=cats[category].subs[0];showView('products');renderProducts();});bindCards(el);}
function trustCard(k,ico){return `<article class="trust-card"><div class="ico">${ico}</div><b>${t(k)}</b><p>${t('placeholder')}</p></article>`}
function catCard(id){return `<button class="category-card ${category===id?'on':''}" data-cat="${id}"><span class="code">0${id}</span><strong>${nCat(id)}</strong><small>${nSub(cats[id].subs[0])} · ${nSub(cats[id].subs[1])}</small><i class="bubble"></i></button>`}
function renderProducts(){const el=$('#v-products');const filtered=products.filter(p=>p.sub.startsWith(category)&&(sub==='all'||p.sub===sub)&&(status==='all'||p.status===status)&&(!query||(`${productName(p)} ${p.code}`).toLowerCase().includes(query.toLowerCase())));el.innerHTML=`<section class="section"><div class="section-head"><div><h2>${t('products')}</h2><p>${t('chooseCategory')}</p></div></div><div class="category-grid">${Object.keys(cats).map(id=>catCard(id)).join('')}</div><div class="subcats" style="margin-top:10px"><button class="pill ${sub==='all'?'on':''}" data-sub="all">${t('allSub')}</button>${cats[category].subs.map(s=>`<button class="pill ${sub===s?'on':''}" data-sub="${s}"><b>${s}</b> · ${nSub(s)}</button>`).join('')}</div><div class="filters"><label class="searchbox">${I.search}<input id="search" value="${esc(query)}" placeholder="${t('search')}"></label><select id="status" class="select"><option value="all">${t('allStatus')}</option><option value="in">${t('available')}</option><option value="out">${t('unavailable')}</option></select></div><div id="productGrid" class="product-grid">${filtered.length?filtered.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1">${t('noProducts')}</div>`}</div></section>`;
$('#status').value=status;const updateGrid=()=>{const list=products.filter(p=>p.sub.startsWith(category)&&(sub==='all'||p.sub===sub)&&(status==='all'||p.status===status)&&(!query||(`${productName(p)} ${p.code}`).toLowerCase().includes(query.toLowerCase())));$('#productGrid').innerHTML=list.length?list.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1">${t('noProducts')}</div>`;bindCards($('#productGrid'));};$$('.category-card',el).forEach(b=>b.onclick=()=>{category=b.dataset.cat;sub=cats[category].subs[0];renderProducts()});$$('.pill',el).forEach(b=>b.onclick=()=>{sub=b.dataset.sub;renderProducts()});$('#status').onchange=e=>{status=e.target.value;updateGrid()};$('#search').oninput=e=>{query=e.target.value;updateGrid()};bindCards(el);}
function productCard(p){const s=subs[p.sub];const quick=[...s.locked.slice(0,1),...s.flex.slice(0,2)];return `<article class="product-card" data-code="${p.code}"><div class="media"><span class="status ${p.status==='out'?'out':''}">${p.status==='out'?t('unavailable'):t('available')}</span><div class="media-track">${[1,2,3].map((x,i)=>`<div class="shot">${garmentSvg(p.sub)}<small>${[t('view1'),t('view2'),t('view3')][i]}</small></div>`).join('')}</div><div class="dots"><i></i><i></i><i></i></div></div><div class="card-body"><div class="product-name">${productName(p)}</div><div class="product-meta"><span>${nCat(s.parent)} / ${nSub(p.sub)}</span><code>${p.code}</code></div><div class="quick-spec">${quick.map(k=>`<span>${s.locked.includes(k)?'🔒 ':''}${nSpec(k)}</span>`).join('')}</div><div class="card-actions"><button class="card-act whatsapp" data-wa="${p.code}" aria-label="${t('whatsapp')}">${I.phone}<span>${t('whatsapp')}</span></button><button class="card-act fav ${favs.has(p.code)?'on':''}" data-fav="${p.code}" aria-label="${t('fav')}">${I.heart}<span>${t('fav')}</span></button><button class="card-act detail" data-detail="${p.code}" aria-label="${t('details')}">${I.info}<span>${t('details')}</span></button></div></div></article>`}
function bindCards(el){$$('[data-wa]',el).forEach(b=>b.onclick=()=>openSales(findP(b.dataset.wa)));$$('[data-fav]',el).forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));$$('[data-detail]',el).forEach(b=>b.onclick=()=>openDetails(findP(b.dataset.detail)));}
function findP(code){return products.find(x=>x.code===code)}
function specHtml(p){const s=subs[p.sub];return `<div class="spec-summary"><span class="legend locked">${I.lock} ${t('locked')}</span><span class="legend flexible">${I.tune} ${t('flexible')}</span></div><div class="spec-grid">${s.locked.map(k=>specItem(k,true)).join('')}${s.flex.map(k=>specItem(k,false)).join('')}</div>`}
function specItem(k,locked){return `<div class="spec-item ${locked?'locked':'flexible'}"><span class="spec-icon">${locked?I.lock:I.tune}</span><span><b>${nSpec(k)}</b><small>${locked?t('fixedHelp'):t('flexHelp')}</small></span></div>`}
function openDetails(p){if(mode==='inline'){const card=$(`.product-card[data-code="${p.code}"]`);$('.inline-detail')?.remove();card.insertAdjacentHTML('afterend',`<section class="inline-detail"><div class="inline-head"><div><b>${productName(p)}</b><div class="product-meta">${t('code')}: ${p.code}</div></div><button class="close" data-close-inline>×</button></div>${specHtml(p)}</section>`);$('[data-close-inline]').onclick=()=>$('.inline-detail')?.remove();$('.inline-detail').scrollIntoView({behavior:'smooth',block:'nearest'});return;}const o=$('#detailOverlay');o.innerHTML=`<div class="scrim"></div><section class="panel" role="dialog" aria-modal="true"><div class="handle"></div><header class="panel-head"><div><b>${productName(p)}</b><div class="product-meta">${t('code')}: ${p.code}</div></div><button class="close">×</button></header><div class="panel-body">${specHtml(p)}</div></section>`;openOverlay(o);}
