function openSales(p){const o=$('#actionOverlay');const paths=[['simple',t('simpleBuy'),I.phone],['stock',t('stockBuy'),I.check],['out',t('outBuy'),I.box]];o.innerHTML=`<div class="scrim"></div><section class="panel" role="dialog" aria-modal="true"><div class="handle"></div><header class="panel-head"><b>${t('salesPathTitle')}</b><button class="close">×</button></header><div class="panel-body"><div class="product-meta" style="margin-bottom:10px"><span>${productName(p)}</span><code>${p.code}</code></div><div class="sales-paths">${paths.map(([id,label,ico])=>`<button class="path-btn" data-sale="${id}"><span class="path-ico">${ico}</span><span><b>${label}</b><small>${nSub(p.sub)} · ${p.status==='in'?t('available'):t('unavailable')}</small></span>${((id==='stock'&&p.status==='in')||(id==='out'&&p.status==='out'))?`<span class="recommended">${t('recommended')}</span>`:''}</button>`).join('')}</div><div id="salePreview"></div></div></section>`;openOverlay(o);$$('[data-sale]',o).forEach(b=>b.onclick=()=>renderSalePreview(p,b.dataset.sale));}
function renderSalePreview(p,path){const titles={simple:t('simpleBuy'),stock:t('stockBuy'),out:t('outBuy')};const message=makeProductMessage(p,titles[path]);$('#salePreview').innerHTML=`<div class="preview"><h4>${t('preview')}</h4><pre>${esc(message)}</pre><div class="wizard-actions"><a class="btn wa" target="_blank" rel="noopener" href="https://wa.me/${PHONE}?text=${encodeURIComponent(message)}">${I.phone}${t('sendWa')}</a></div></div>`;}
function makeProductMessage(p,title){return `${title}\n${t('products')}: ${productName(p)}\n${t('code')}: ${p.code}\n${nCat(subs[p.sub].parent)} / ${nSub(p.sub)}\n${p.status==='in'?t('available'):t('unavailable')}`}
function openOverlay(o){o.classList.add('open');document.body.style.overflow='hidden';const close=()=>{o.classList.remove('open');document.body.style.overflow='';};$('.scrim',o).onclick=close;$('.close',o).onclick=close;document.onkeydown=e=>{if(e.key==='Escape')close()};}
function toggleFav(code){favs.has(code)?favs.delete(code):favs.add(code);localStorage.setItem('armaghan-favorites-v2',JSON.stringify([...favs]));toast(favs.has(code)?t('added'):t('removed'));renderProducts();renderFavorites();}
function renderFavorites(){const el=$('#v-favorites');const list=products.filter(p=>favs.has(p.code));el.innerHTML=`<section class="section"><div class="section-head"><div><h2>${t('favorites')}</h2><p>${list.length} ${t('products')}</p></div>${list.length?`<button id="shareFav" class="btn ghost spacer">${t('shareFav')}</button>`:''}</div>${list.length?`<div class="fav-list">${list.map(p=>`<div class="fav-row"><div class="fav-thumb">${garmentSvg(p.sub)}</div><div class="meta"><b>${productName(p)}</b><small>${t('code')}: ${p.code}</small></div><button class="card-act whatsapp" data-wa="${p.code}">${I.phone}</button><button class="card-act fav on" data-fav="${p.code}">${I.heart}</button></div>`).join('')}</div>`:`<div class="empty">${t('emptyFav')}</div>`}</section>`;bindCards(el);if($('#shareFav'))$('#shareFav').onclick=shareFavorites;}
async function shareFavorites(){const u=new URL(location.href);u.searchParams.set('favorites',[...favs].join(','));u.hash='favorites';try{if(navigator.share)await navigator.share({title:t('favorites'),url:u.toString()});else{await navigator.clipboard.writeText(u.toString());toast(t('linkCopied'));}}catch(e){}}
function renderProduction(){const el=$('#v-production');const paths=[['custom','custom','customDesc',I.wand],['brand','brandOrder','brandDesc',I.tag],['pack','packOrder','packDesc',I.box]];let body='';if(orderState.step===0){body=`<div class="production-paths">${paths.map(([id,k,d,ico])=>`<button class="path-btn" data-prodpath="${id}"><span class="path-ico">${ico}</span><span><b>${t(k)}</b><small>${t(d)}</small></span></button>`).join('')}</div>`;}else if(orderState.step===1){body=`<h3>${t('chooseMain')}</h3><div class="choice-grid">${Object.keys(cats).map(id=>`<button class="choice" data-ocat="${id}"><b>0${id} · ${nCat(id)}</b><small>${nSub(cats[id].subs[0])} · ${nSub(cats[id].subs[1])}</small></button>`).join('')}</div>`;}else if(orderState.step===2){body=`<h3>${t('chooseSubcat')}</h3><div class="choice-grid">${cats[orderState.cat].subs.map(id=>`<button class="choice" data-osub="${id}"><b>${id} · ${nSub(id)}</b><small>${nCat(orderState.cat)}</small></button>`).join('')}</div>`;}else{const pseudo={sub:orderState.sub};const title=orderState.path==='custom'?t('custom'):orderState.path==='brand'?t('brandOrder'):t('packOrder');const message=makeOrderMessage(title);body=`<h3>${t('specStep')}</h3>${specHtml(pseudo)}<label style="display:block;margin-top:12px"><b>${t('orderNote')}</b><textarea id="orderNote" class="note" placeholder="${t('orderNote')}">${esc(orderState.note)}</textarea></label><div class="preview"><h4>${t('preview')}</h4><pre id="orderPreview">${esc(message)}</pre></div><div class="wizard-actions"><a id="orderWa" class="btn wa" target="_blank" rel="noopener" href="https://wa.me/${PHONE}?text=${encodeURIComponent(message)}">${I.phone}${t('sendWa')}</a></div>`;}
el.innerHTML=`<section class="section"><div class="section-head"><div><h2>${t('prodTitle')}</h2><p>${t('heroText')}</p></div></div><div class="wizard"><div class="steps">${[0,1,2,3].map(x=>`<i class="step-dot ${x<=orderState.step?'on':''}"></i>`).join('')}</div>${body}${orderState.step>0?`<div class="wizard-actions"><button id="orderBack" class="btn ghost">${t('back')}</button></div>`:''}</div></section>`;
$$('[data-prodpath]',el).forEach(b=>b.onclick=()=>{orderState={step:1,path:b.dataset.prodpath,cat:null,sub:null,note:''};renderProduction()});$$('[data-ocat]',el).forEach(b=>b.onclick=()=>{orderState.cat=b.dataset.ocat;orderState.step=2;renderProduction()});$$('[data-osub]',el).forEach(b=>b.onclick=()=>{orderState.sub=b.dataset.osub;orderState.step=3;renderProduction()});if($('#orderBack'))$('#orderBack').onclick=()=>{orderState.step--;if(orderState.step===0)orderState={step:0,path:null,cat:null,sub:null,note:''};renderProduction()};if($('#orderNote'))$('#orderNote').oninput=e=>{orderState.note=e.target.value;const title=orderState.path==='custom'?t('custom'):orderState.path==='brand'?t('brandOrder'):t('packOrder');const m=makeOrderMessage(title);$('#orderPreview').textContent=m;$('#orderWa').href=`https://wa.me/${PHONE}?text=${encodeURIComponent(m)}`};}
function makeOrderMessage(title){const s=subs[orderState.sub];return `${title}\n${t('chooseMain')}: ${nCat(orderState.cat)}\n${t('chooseSubcat')}: ${nSub(orderState.sub)} (${orderState.sub})\n${t('negotiable')}: ${s.flex.map(nSpec).join('، ')}\n${t('fixed')}: ${s.locked.length?s.locked.map(nSpec).join('، '):'—'}${orderState.note?`\n${t('orderNote')}: ${orderState.note}`:''}`}
function renderTracking(){const el=$('#v-tracking');el.innerHTML=`<section class="section"><div class="section-head"><div><h2>${t('trackingTitle')}</h2><p>${t('loginDemo')}</p></div></div><div class="track-grid"><article class="track-card"><h3>${t('reorder')}</h3><p>${t('demoAction')}</p><button class="btn ghost demo-act">${t('reorder')}</button></article><article class="track-card"><h3>${t('timeline')}</h3><div class="timeline"><div><i class="done"></i>${t('preview')}</div><div><i class="done"></i>${t('prepay')}</div><div><i></i>${t('tracking')}</div></div></article><article class="track-card"><h3>${t('prepay')}</h3><p>${t('demoAction')}</p><button class="btn ghost demo-act">${t('prepay')}</button></article><article class="track-card"><h3>${t('customerAccess')}</h3><p>${t('loginDemo')}</p><div class="wizard-actions"><button class="btn ghost demo-act">Google / Email</button><button class="btn ghost demo-act">User / Pass</button><button class="btn ghost demo-act">Private Link</button></div></article><article class="track-card"><h3>${t('install')}</h3><p>${t('installHint')}</p><button id="installBtn" class="btn ghost">${t('install')}</button></article></div></section>`;$$('.demo-act',el).forEach(b=>b.onclick=()=>toast(t('demoAction')));$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast(t('installHint'));};}
function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function hydrateShared(){const q=new URLSearchParams(location.search).get('favorites');if(q){q.split(',').filter(Boolean).forEach(c=>{if(products.some(p=>p.code===c))favs.add(c)});localStorage.setItem('armaghan-favorites-v2',JSON.stringify([...favs]));}if(location.hash==='#favorites')setTimeout(()=>showView('favorites'),0)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('../pwa-sw.js',{scope:'../'}).catch(()=>{}));
layout();hydrateShared();
