'use strict';
const PHONE='989381009231';
const mode=document.body.dataset.variant||'sheet';
const testNo=document.body.dataset.test||'10';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const I={
 home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 10.8 12 3l9 7.8v9.1a1.1 1.1 0 0 1-1.1 1.1H4.1A1.1 1.1 0 0 1 3 19.9z"/><path d="M9 21v-7h6v7"/></svg>',
 grid:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
 wand:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m4 20 10-10"/><path d="m14 4 .7 2.1L17 7l-2.3.9L14 10l-.8-2.1L11 7l2.2-.9zM19 12l.6 1.6 1.4.6-1.4.6L19 16l-.6-1.2-1.4-.6 1.4-.6zM6 4l.6 1.4L8 6l-1.4.6L6 8l-.6-1.4L4 6l1.4-.6z"/></svg>',
 heart:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.8 4.7a5.3 5.3 0 0 0-7.5 0L12 6l-1.3-1.3a5.3 5.3 0 1 0-7.5 7.5L12 21l8.8-8.8a5.3 5.3 0 0 0 0-7.5Z"/></svg>',
 track:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5"/></svg>',
 search:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',
 chevron:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m9 18 6-6-6-6"/></svg>',
 lock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',
 tune:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M7 12h10M10 18h4"/></svg>',
 info:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></svg>',
 phone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11.5a8.3 8.3 0 0 1-9 8.2 9.6 9.6 0 0 1-3.7-1.3L3 19.5l1.2-4.1A8.3 8.3 0 1 1 20 11.5Z"/><path d="M8.4 7.8c.4-.4.8-.2 1 .2l.8 1.7c.2.4 0 .7-.3 1l-.5.5c.6 1.3 1.6 2.3 2.9 2.9l.5-.5c.3-.3.6-.5 1-.3l1.7.8c.4.2.6.6.2 1-.6.8-1.4 1.1-2.4.9-3.4-.7-6-3.3-6.7-6.7-.2-1 .1-1.9.9-2.5Z"/></svg>',
 box:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m4 7 8-4 8 4-8 4z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></svg>',
 tag:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 13 13 20 4 11V4h7z"/><circle cx="8.5" cy="8.5" r="1.5"/></svg>',
 check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg>'
};
const tx={
 fa:{dir:'rtl',brand:'ارمغان',tagline:'تولید و صادرات پوشاک',home:'خانه',products:'محصولات',production:'سفارش تولید',favorites:'مطلوب‌ها',tracking:'پیگیری',heroTitle:'کاتالوگ روشن، مذاکره ساده، سفارش مستقیم',heroText:'محصول را بر اساس دسته و زیردسته پیدا کنید؛ مشخصات ثابت را با قفل ببینید و موارد قابل مذاکره را برای گفتگو در واتساپ آماده کنید.',browse:'مشاهده محصولات',startOrder:'شروع سفارش تولید',brandIntro:'معرفی تولیدکننده',capabilities:'توانمندی‌ها',docs:'اعتبارات و اسناد',sales:'ارتباط فروش',placeholder:'اطلاعات این بخش در نسخه نهایی توسط کسب‌وکار تکمیل می‌شود.',chooseCategory:'دسته محصول را انتخاب کنید',chooseSub:'سپس زیردسته را مشخص کنید',search:'جستجوی نام یا کد محصول',allStatus:'همه وضعیت‌ها',available:'موجود',unavailable:'ناموجود',allSub:'همه زیردسته‌ها',demo:'محتوا و تصاویر این تست نمونه‌اند؛ ساختار دسته‌بندی و قفل‌ها از فایل اکسل شما استخراج شده است.',code:'کد',details:'مشخصات',whatsapp:'واتساپ',fav:'مطلوب',locked:'غیرقابل تغییر',flexible:'قابل مذاکره',fixedHelp:'این مشخصات برای این زیردسته ثابت اعلام شده‌اند.',flexHelp:'این موارد می‌توانند در مذاکره فروش سفارشی شوند.',salesPathTitle:'مسیر پیام واتساپ',simpleBuy:'خرید ساده',stockBuy:'خرید موجود',outBuy:'خرید ناموجود',recommended:'پیشنهادی',preview:'پیش‌نمایش پیام',sendWa:'ادامه در واتساپ',added:'به لیست مطلوب‌ها اضافه شد',removed:'از لیست مطلوب‌ها حذف شد',emptyFav:'هنوز محصولی در مطلوب‌ها نیست.',shareFav:'ارسال لینک مطلوب‌ها',linkCopied:'لینک لیست آماده شد',prodTitle:'سه مسیر تولید',custom:'تولید سفارشی',brandOrder:'سفارش تولید با برند',packOrder:'سفارش تولید با بسته‌بندی',customDesc:'مشخصات قابل مذاکره را برای تولید جدید مشخص کنید.',brandDesc:'تولید محصول با عنوان و برند سفارش‌دهنده.',packDesc:'تولید با نیازهای بسته‌بندی موردنظر سفارش‌دهنده.',next:'ادامه',back:'بازگشت',chooseMain:'دسته اصلی',chooseSubcat:'زیردسته',specStep:'مشخصات و پیام',orderNote:'توضیح تکمیلی برای فروشنده',negotiable:'قابل مذاکره',fixed:'ثابت',trackingTitle:'پیگیری و دسترسی مشتری',reorder:'سفارش مجدد',timeline:'تایم‌لاین سفارش',prepay:'تأیید پیش‌پرداخت',customerAccess:'دسترسی مشتری',loginDemo:'ورود با Google/ایمیل، نام کاربری و لینک خصوصی در نسخه واقعی نیازمند بک‌اند امن است.',demoAction:'این قابلیت در نمونه نمایشی شبیه‌سازی شده است.',noProducts:'محصولی با این فیلتر پیدا نشد.',model:'مدل آزمایشی',view1:'نمای اصلی',view2:'نمای دوم',view3:'جزئیات',install:'نصب برنامه',installHint:'نسخه PWA برای دسترسی سریع‌تر آماده شده است.'},
 ar:{dir:'rtl',brand:'أرمغان',tagline:'إنتاج وتصدير الملابس',home:'الرئيسية',products:'المنتجات',production:'طلب إنتاج',favorites:'المفضلة',tracking:'المتابعة',heroTitle:'كتالوج واضح، تفاوض أسهل، تواصل مباشر',heroText:'اختر الفئة والفئة الفرعية، شاهد المواصفات الثابتة بعلامة القفل وحدد البنود القابلة للتفاوض قبل واتساب.',browse:'عرض المنتجات',startOrder:'بدء طلب إنتاج',brandIntro:'تعريف المنتج',capabilities:'القدرات',docs:'الوثائق والاعتمادات',sales:'التواصل التجاري',placeholder:'تُستكمل بيانات هذا القسم من قبل الشركة في النسخة النهائية.',chooseCategory:'اختر فئة المنتج',chooseSub:'ثم اختر الفئة الفرعية',search:'ابحث بالاسم أو الكود',allStatus:'كل الحالات',available:'متوفر',unavailable:'غير متوفر',allSub:'كل الفئات الفرعية',demo:'المحتوى والصور تجريبية؛ بنية الفئات وحالات القفل مستخرجة من ملف Excel المرفق.',code:'الكود',details:'المواصفات',whatsapp:'واتساب',fav:'مفضلة',locked:'غير قابل للتغيير',flexible:'قابل للتفاوض',fixedHelp:'هذه المواصفات ثابتة لهذه الفئة الفرعية.',flexHelp:'يمكن تخصيص هذه البنود أثناء التفاوض.',salesPathTitle:'مسار رسالة واتساب',simpleBuy:'شراء بسيط',stockBuy:'شراء متوفر',outBuy:'شراء غير متوفر',recommended:'مقترح',preview:'معاينة الرسالة',sendWa:'متابعة في واتساب',added:'تمت الإضافة إلى المفضلة',removed:'تمت الإزالة من المفضلة',emptyFav:'لا توجد منتجات في المفضلة بعد.',shareFav:'مشاركة رابط المفضلة',linkCopied:'تم تجهيز رابط القائمة',prodTitle:'ثلاثة مسارات للإنتاج',custom:'إنتاج مخصص',brandOrder:'إنتاج بعلامتك التجارية',packOrder:'إنتاج بتغليف مخصص',customDesc:'حدد البنود القابلة للتفاوض لإنتاج جديد.',brandDesc:'إنتاج المنتج بعلامة العميل.',packDesc:'إنتاج مع متطلبات تغليف العميل.',next:'متابعة',back:'رجوع',chooseMain:'الفئة الرئيسية',chooseSubcat:'الفئة الفرعية',specStep:'المواصفات والرسالة',orderNote:'ملاحظة إضافية للبائع',negotiable:'قابل للتفاوض',fixed:'ثابت',trackingTitle:'المتابعة ودخول العميل',reorder:'إعادة الطلب',timeline:'الخط الزمني للطلب',prepay:'تأكيد الدفعة المقدمة',customerAccess:'دخول العميل',loginDemo:'تسجيل Google/البريد واسم المستخدم والرابط الخاص يحتاج إلى خادم آمن في النسخة الفعلية.',demoAction:'هذه الوظيفة محاكاة في النموذج.',noProducts:'لا توجد منتجات مطابقة.',model:'نموذج تجريبي',view1:'الصورة الرئيسية',view2:'الصورة الثانية',view3:'التفاصيل',install:'تثبيت التطبيق',installHint:'نسخة PWA جاهزة للوصول السريع.'},
 en:{dir:'ltr',brand:'Armaghan',tagline:'Garment production & export',home:'Home',products:'Products',production:'Production',favorites:'Favorites',tracking:'Tracking',heroTitle:'Clear catalog, easier negotiation, direct handoff',heroText:'Choose a category and subcategory, see locked specifications at a glance, and prepare negotiable items before WhatsApp.',browse:'Browse products',startOrder:'Start production request',brandIntro:'Manufacturer profile',capabilities:'Capabilities',docs:'Documents & credentials',sales:'Sales contact',placeholder:'This area is intentionally left for business-verified content in the final version.',chooseCategory:'Choose a product category',chooseSub:'Then choose a subcategory',search:'Search product name or code',allStatus:'All statuses',available:'Available',unavailable:'Unavailable',allSub:'All subcategories',demo:'Content and imagery are mock. Category structure and lock states come from your Excel file.',code:'Code',details:'Specifications',whatsapp:'WhatsApp',fav:'Favorite',locked:'Locked',flexible:'Negotiable',fixedHelp:'These specifications are fixed for this subcategory.',flexHelp:'These items can be discussed and customized during sales negotiation.',salesPathTitle:'WhatsApp message path',simpleBuy:'Simple purchase',stockBuy:'Buy available',outBuy:'Request unavailable',recommended:'Suggested',preview:'Message preview',sendWa:'Continue to WhatsApp',added:'Added to Favorites',removed:'Removed from Favorites',emptyFav:'No favorite products yet.',shareFav:'Share Favorites link',linkCopied:'List link is ready',prodTitle:'Three production paths',custom:'Custom production',brandOrder:'Production with your brand',packOrder:'Production with custom packaging',customDesc:'Select negotiable specifications for a new production request.',brandDesc:'Produce the item with the buyer’s brand.',packDesc:'Produce with the buyer’s packaging requirements.',next:'Continue',back:'Back',chooseMain:'Main category',chooseSubcat:'Subcategory',specStep:'Specs & message',orderNote:'Additional note for seller',negotiable:'Negotiable',fixed:'Fixed',trackingTitle:'Customer access & tracking',reorder:'Reorder',timeline:'Order timeline',prepay:'Confirm prepayment',customerAccess:'Customer access',loginDemo:'Google/email SSO, username/password and private links require a secure backend in the real product.',demoAction:'This feature is simulated in the prototype.',noProducts:'No products match this filter.',model:'Demo model',view1:'Main view',view2:'Second view',view3:'Detail',install:'Install app',installHint:'PWA shell is ready for faster access.'},
 ku:{dir:'rtl',brand:'ئەرماخان',tagline:'بەرهەمهێنان و هەناردەی جل و بەرگ',home:'ماڵەوە',products:'بەرهەمەکان',production:'داواکاری بەرهەم',favorites:'دڵخوازەکان',tracking:'بەدواداچوون',heroTitle:'کاتەلۆگی ڕوون، گفتوگۆی ئاسان، پەیوەندی ڕاستەوخۆ',heroText:'پۆل و ژێرپۆل هەڵبژێرە، تایبەتمەندییە جێگیرەکان بە قفڵ ببینە و بڕگەی گفتوگۆپێکراو بۆ واتساپ ئامادە بکە.',browse:'بینینی بەرهەمەکان',startOrder:'دەستپێکردنی داواکاری',brandIntro:'ناساندنی بەرهەمهێنەر',capabilities:'تواناکان',docs:'بەڵگە و متمانە',sales:'پەیوەندی فرۆشتن',placeholder:'زانیاری ئەم بەشە لە وەشانی کۆتایی لەلایەن بازرگانییەوە پڕدەکرێتەوە.',chooseCategory:'پۆلی بەرهەم هەڵبژێرە',chooseSub:'پاشان ژێرپۆل دیاری بکە',search:'گەڕان بە ناو یان کۆد',allStatus:'هەموو دۆخەکان',available:'بەردەست',unavailable:'بەردەست نییە',allSub:'هەموو ژێرپۆلەکان',demo:'ناوەڕۆک و وێنەکان نموونەن؛ پۆل‌بەندی و قفڵەکان لە فایلی Excel وەرگیراون.',code:'کۆد',details:'تایبەتمەندی',whatsapp:'واتساپ',fav:'دڵخواز',locked:'گۆڕانکاری ناکرێت',flexible:'قابل گفتوگۆ',fixedHelp:'ئەم تایبەتمەندییانە بۆ ئەم ژێرپۆلە جێگیرن.',flexHelp:'ئەم بڕگانە دەتوانرێت لە گفتوگۆی فرۆشتندا بگۆڕدرێن.',salesPathTitle:'ڕێگای پەیامی واتساپ',simpleBuy:'کڕینی سادە',stockBuy:'کڕینی بەردەست',outBuy:'داواکاری نابەردەست',recommended:'پێشنیارکراو',preview:'پێشبینینی پەیام',sendWa:'بەردەوامبوون لە واتساپ',added:'زیادکرا بۆ دڵخوازەکان',removed:'لابرا لە دڵخوازەکان',emptyFav:'هێشتا بەرهەمێکی دڵخواز نییە.',shareFav:'ناردنی لینکی دڵخوازەکان',linkCopied:'لینکی لیست ئامادەیە',prodTitle:'سێ ڕێگای بەرهەمهێنان',custom:'بەرهەمهێنانی تایبەت',brandOrder:'بەرهەمهێنان بە براند',packOrder:'بەرهەمهێنان بە پاکەت',customDesc:'تایبەتمەندییە گفتوگۆپێکراوەکان دیاری بکە.',brandDesc:'بەرهەم بە براندی داواکار.',packDesc:'بەرهەم بە پێداویستی پاکەتکردنی داواکار.',next:'بەردەوام',back:'گەڕانەوە',chooseMain:'پۆلی سەرەکی',chooseSubcat:'ژێرپۆل',specStep:'تایبەتمەندی و پەیام',orderNote:'تێبینی بۆ فرۆشیار',negotiable:'قابل گفتوگۆ',fixed:'جێگیر',trackingTitle:'بەدواداچوون و دەستگەیشتنی کڕیار',reorder:'داواکاری دووبارە',timeline:'هێڵی کاتی داواکاری',prepay:'پشتڕاستکردنەوەی پێش‌پارە',customerAccess:'دەستگەیشتنی کڕیار',loginDemo:'چوونەژوورەوەی Google/ئیمەیڵ، ناوی بەکارهێنەر و لینکی تایبەت لە وەشانی ڕاستەقینەدا پێویستی بە backendی پارێزراو هەیە.',demoAction:'ئەم تایبەتمەندییە لە نموونەکەدا شبیه‌سازی کراوە.',noProducts:'هیچ بەرهەمێک نەدۆزرایەوە.',model:'مۆدێلی نموونە',view1:'دیمەنی سەرەکی',view2:'دیمەنی دووەم',view3:'وردەکاری',install:'دامەزراندن',installHint:'پووشی PWA بۆ دەستگەیشتنی خێراتر ئامادەیە.'}
};
